server.port=8083

# Datasource với biến môi trường (có giá trị mặc định dùng public Railway)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://acela.proxy.rlwy.net:22604/railway?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:CiYTS1ChiADBaeNTXAiaaLNCiFcBdfFIY}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT với biến môi trường (giữ giá trị mặc định)
jwt.secret=${JWT_SECRET:Z0Z6QnR1T3pXQk9ZbE1nWjJrY0h2cE9mS1J3Z1JzR1lZb0d2bFZxQ1hKcG5vN0xUeQ==}
jwt.expiration=${JWT_EXPIRATION:86400000}