server.port=8083

spring.datasource.url=jdbc:postgresql://db.mityssimayywcsjsesew.supabase.co:5432/postgres?user=postgres&password=wzXc4uvM7d3fFbPU&sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${SUPABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.show-sql=true

jwt.secret=Z0Z6QnR1T3pXQk9ZbE1nWjJrY0h2cE9mS1J3Z1JzR1lZb0d2bFZxQ1hKcG5vN0xUeQ==
jwt.expiration=86400000