server.port=8083

spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL55Dialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

dev.truong = Truong Quang Hop
spring.profiles.active=uat

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=${FILE_UPLOAD_DIR:../docker-uploads}

# Spring profile (có thể dùng biến môi trường hoặc argument)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

# Storage type
storage.type=${STORAGE_TYPE:local}

# Cloudinary config (đọc từ biến môi trường)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}